import {CHALLENGES} from './exercises.js';
import {restoreSession} from './session.js';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function activityReport(raw,identity,exportedAt=new Date().toISOString()){
 const session=restoreSession(raw);
 const rows=CHALLENGES.map(task=>{
  const events=session.history.filter(e=>e.id===task.id),answers=events.filter(e=>e.kind==='answer'),help=events.filter(e=>e.kind==='help'),result=session.results.find(r=>r.id===task.id);
  return {id:task.id,target:`${task.from.n}/${task.from.d}`,pieces:task.to,family:task.family,responses:answers.map(a=>({fraction:`${a.n}/${task.to}`,correct:a.correct})),help:help.map(h=>h.source),attempts:answers.length,retries:Math.max(0,answers.length-1),complete:!!result,firstWithoutHelp:result?.firstTry??false};
 });
 const summary={completed:session.results.length,total:CHALLENGES.length,firstWithoutHelp:rows.filter(r=>r.firstWithoutHelp).length,helped:rows.filter(r=>r.help.length).length,retried:rows.filter(r=>r.retries).length};
 const metadata={activity:'EasyAsPie Bakery Orders',exportedAt,build:identity,startedBuild:session.originBuild,summary,orders:rows};
 const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EasyAsPie Activity Report</title><style>body{font-family:'Comic Sans MS','Comic Sans',cursive;color:#34243d;background:#fffaf0;margin:2rem auto;max-width:1100px;padding:0 1rem}h1,h2{color:#63358d}table{width:100%;border-collapse:collapse;background:white;font-size:13px}th,td{border:1px solid #ccb997;padding:8px;text-align:left;vertical-align:top}th{background:#ecdfba}code{overflow-wrap:anywhere}small{display:block} @media print{body{margin:0;background:white}tr{break-inside:avoid}}</style><h1>EasyAsPie Activity Report</h1><p>${summary.completed} of ${summary.total} orders completed. ${summary.firstWithoutHelp} first answers correct without recorded help; ${summary.helped} orders with help; ${summary.retried} orders retried.</p><p>Anonymous practice evidence. Hints, reference/vocabulary use, Learn visits and Free Play detours during an unfinished order count as help. This report does not establish unaided performance or ruler-reading mastery. No information was sent to a server.</p><h2>Build And Session</h2><p>Exported: ${escape(exportedAt)}<br>Build: <code>${escape(identity.id)}</code><br>Version: ${escape(identity.version)} · Codename: ${escape(identity.codename||'Unassigned')} · Build UTC: ${escape(identity.builtAt)}<br>Source: <code>${escape(identity.sha)}</code> (${identity.dirty?'dirty':'clean'})<br>Session started in: <code>${escape(session.originBuild||'Not recorded')}</code></p><h2>Responses And Help</h2><table><thead><tr><th>Order / Target</th><th>Requested Pieces</th><th>Submitted Responses In Order</th><th>Retries / Help Used</th><th>Result</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}. ${escape(r.target)}<small>${escape(r.family)}</small></td><td>${r.pieces}</td><td>${r.responses.map(a=>`${escape(a.fraction)} — ${a.correct?'Correct':'Not Yet'}`).join('<br>')||'No submission'}</td><td>${r.attempts} attempts; ${r.retries} retries<br>${r.help.map(escape).join(', ')||'No recorded help'}</td><td>${r.complete?'Completed':'Incomplete'}${r.firstWithoutHelp?'<br>First answer correct, no recorded help':''}</td></tr>`).join('')}</tbody></table></html>`;
 return {html,metadata};
}
