const terms={whole:{title:'Whole',text:'One complete pie or one entire bar. Every whole pie here has the same size.'},numerator:{title:'Numerator',text:'The top number counts selected equal parts. In 3/8, three eighths are selected.'},denominator:{title:'Denominator',text:'The bottom number counts all equal parts in one {whole}. In 3/8, there are eight equal parts in the whole.'},equivalent:{title:'Equivalent Fractions',text:'Different fraction names for the same amount of the same-sized {whole}. For example, 1/2 = 2/4 = 4/8 = 8/16.'},mixed:{title:'Mixed Number',text:'A whole number and a proper fraction together. Here, 1 whole + 1/4 uses a full plate and a quarter of another equal whole.'},regroup:{title:'Regroup',text:'Combine equal parts into larger equal parts without changing the amount. Free Play can regroup when both counts divide by two exactly.'}};
export function term(key){const t=terms[key];return `<span class="term" tabindex="0" role="button" data-term="${key}" aria-label="Open ${t.title} Reference"><b>${t.title}</b><span class="term-tip" role="tooltip">${t.text.replace(/\{(\w+)\}/g,(_,k)=>term(k))}<small>Click or press Enter for the reference.</small></span></span>`;}
export function installReference(onHelp){
 const dialog=document.createElement('dialog');dialog.id='fraction-reference';dialog.innerHTML=`<div class="reference-head"><span aria-hidden="true">◔</span><h2>Fraction Reference</h2><button id="close-reference" aria-label="Close Fraction Reference">Close ×</button></div><div class="reference-content" tabindex="0"><p>A little recipe for understanding fractions. Keep the same-sized ${term('whole')} throughout.</p>${Object.entries(terms).map(([key,t])=>`<section id="reference-${key}"><h3>${t.title}</h3><p>${t.text.replace(/\{(\w+)\}/g,(_,k)=>term(k))}</p></section>`).join('')}<h3>Build And Revise</h3><p>Start on an empty unit to ADD. Start on a filled unit to ERASE. Keep dragging; the operation stays the same. Purple previews add, red previews erase. CUT PIES checks your answer. A wrong answer keeps your work so you can revise it.</p><h3>Keyboard And Touch</h3><p>Tap individual pieces, or use the numbered unit controls in each Pie Card. Tab to a pie or bar; arrows, Home and End explore. Enter or Space toggles one unit. Shift + arrows previews a run, Enter commits, Escape cancels. Background drags move the camera. Use the camera buttons or Reset View at any time.</p><h3>Free Play</h3><p>Select a piece to serve it and all earlier pieces. Cut and Regroup change equal subdivisions while preserving the amount. These are different from CUT PIES, which checks an order.</p></div>`;document.body.append(dialog);
 let returnFocus=null;
 const open=key=>{onHelp('reference');returnFocus=document.activeElement;dialog.showModal();if(key)dialog.querySelector('#reference-'+key)?.scrollIntoView({block:'nearest'});document.querySelector('#close-reference').focus();};
 dialog.querySelector('#close-reference').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{if(returnFocus?.isConnected)returnFocus.focus();});
 document.addEventListener('click',e=>{const target=e.target.closest('[data-term],[data-reference]');if(!target)return;e.stopPropagation();if(!dialog.open)open(target.dataset.term);else if(target.dataset.term)dialog.querySelector('#reference-'+target.dataset.term)?.scrollIntoView({block:'nearest'});});
 document.addEventListener('keydown',e=>{if(e.target.matches('.term')&&['Enter',' '].includes(e.key)){e.preventDefault();if(!dialog.open)open(e.target.dataset.term);}});
 for(const event of ['pointerover','focusin'])document.addEventListener(event,e=>{const target=e.target.closest?.('.term');if(target&&!target.contains(e.relatedTarget))onHelp('vocabulary');});
 return dialog;
}
